name: Release New Version
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: volar-component-types
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"refactor","section":"Refactors","hidden":false}]'
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: Install PNPM
        if: ${{ steps.release.outputs.release_created }}
        run: npm i -g pnpm
      - name: Lint and Test
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm i --frozen-lockfile && pnpm build
      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
